### ISSUE TITLE
Loki Config Missing

### ISSUE THREAD

**Issue by seidenbergerscott** [kilnfi/eth-validator-watcher#68]
I am trying to get the dashboard up and running and I don't see any references to configuring Loki in the repo, is there a config for that or a procedure so I can add it as a datasource in Grafana? It doesn't seem to be included in the Dockerfile or as a Poetry dependency. Thanks!

**Comment by nalepae** [comment]
Hi @seidenbergerscott , thanks for your message!

If, in Grafana, you choose `+`/`Import Dashboard` then you copy paste the content of this file, you should get this screen:

<img width="823" alt="image" src="https://github.com/kilnfi/eth-validator-watcher/assets/4943830/210a157a-7c4a-4a05-b686-33112f4e0d86">.

The two fields on the bottom let you choose your Prometheus/Loki data source.
Note this should work from today only, since before the Grafana Dashboard was not exported correctly.

https://github.com/kilnfi/eth-validator-watcher/blob/main/grafana_dashboard.json

Please re-open this ticket if needed!
